force-app/main/default/objects/Batch_Size__mdt/Batch_Size__mdt.object-meta.xml
<CustomObject>
    <description>The number of records processed for each batch in the execute method of an Apex Batch Class.</description>
    <label>Batch Size</label>
    <pluralLabel>Batch Sizes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Batch_Size__mdt/fields/Number_of_Records__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Records__c</fullName>
    <description>Number of records to process per each batch.</description>
    <label>Number of Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/bg_JourneyScheduledJobs.cls
public inherited sharing class bg_JourneyScheduledJobs implements Schedulable {
    private Batch_Size__mdt batchSize;
    @testVisible private Integer recordsToProcess;

    @testVisible private Integer getNumberOfRecordsToProcess()
    {
        if (recordsToProcess == null)
        {
            batchSize = Batch_Size__mdt.getInstance('Batch_Size');
            recordsToProcess = (Integer) batchSize.Number_of_Records__c;
        }
        if (recordsToProcess == null)
        {
            recordsToProcess = 2000;
        }
        return recordsToProcess;     
    }

    public void execute(SchedulableContext ctx)
    {
        bg_JourneyTasksProgressSendEmail journeyTasksProgressEmail = new bg_JourneyTasksProgressSendEmail();
        Database.executeBatch(journeyTasksProgressEmail, getNumberOfRecordsToProcess());
    }

}