force-app/main/default/objects/JourneyTask__c/JourneyTask__c.object-meta.xml
<CustomObject>
    <description>Add a Task related to the Journey Object.</description>
    <label>Journey Task</label>
    <nameField>
        <label>Journey Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journey Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JourneyTask__c/fields/RelativeDaystoComplete__c.field-meta.xml
<CustomField>
    <fullName>RelativeDaystoComplete__c</fullName>
    <description>Indicates the period in which the Task needs to be completed.</description>
    <label>Relative Days to Complete</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/bg_JourneyTaskService.cls
public inherited sharing class bg_JourneyTaskService implements bg_JourneyTaskService_IF{

    public static void handleNegativeCompletionDays(List<JourneyTask__c> oldJourneyTasksValues, List<JourneyTask__c> updatedJourneyTasksValues)
    {
        for (Integer i = 0; i < oldJourneyTasksValues.size(); i++)
        {
            if ((oldJourneyTasksValues[i].RelativeDaystoComplete__c + updatedJourneyTasksValues[i].RelativeDaystoComplete__c) <= 0)
            {
                updatedJourneyTasksValues[i].addError(System.Label.Negative_Value_Days_to_Complete_Error_Msg);
            }
        }
    }
}