force-app/main/default/objects/JourneyTask__c/JourneyTask__c.object-meta.xml
<CustomObject>
    <description>Add a Task related to the Journey Object.</description>
    <label>Journey Task</label>
    <nameField>
        <label>Journey Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journey Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JourneyTask__c/fields/RelativeDaystoComplete__c.field-meta.xml
<CustomField>
    <fullName>RelativeDaystoComplete__c</fullName>
    <description>Indicates the period in which the Task needs to be completed.</description>
    <label>Relative Days to Complete</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/bg_JourneyController.cls
public inherited sharing class bg_JourneyController {
    @AuraEnabled(cacheable=true)
    public static List<JourneyTask__c> getJourneyTasks(Id journeyId)
    {
       return bg_DataAccessor.getJourneyTasks(journeyId);
    }

    @AuraEnabled
    public static List<JourneyTask__c> relativeDaysToCompleteMassIncrementBySameAmount(Id journeyId, Integer daysToComplete)
    {
        List<JourneyTask__c> tasksToUpdate = bg_DataAccessor.getJourneyTasks(journeyId);
        
        for (JourneyTask__c task : tasksToUpdate)
        {
            task.RelativeDaystoComplete__c += daysToComplete;
        }
        update tasksToUpdate;
        return tasksToUpdate;
    }
    
}