force-app/main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <description>Candidate Progress Tracking</description>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journey__c/fields/CandidateName__c.field-meta.xml
<CustomField>
    <fullName>CandidateName__c</fullName>
    <description>Candidate Name</description>
    <label>Candidate Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journey__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Apply s specific Template to this Journey.</description>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/JourneyTask__c.object-meta.xml
<CustomObject>
    <description>Add a Task related to the Journey Object.</description>
    <label>Journey Task</label>
    <nameField>
        <label>Journey Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journey Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JourneyTask__c/fields/CompletionStatus__c.field-meta.xml
<CustomField>
    <fullName>CompletionStatus__c</fullName>
    <description>Indicates the status for each task.</description>
    <formula>IF( Completed__c , &quot;Complete&quot;, IF( Today() &gt; EstimatedCompletionDate__c , &quot;Overdue&quot;, &quot;In Progress&quot;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Completion Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/fields/EstimatedCompletionDate__c.field-meta.xml
<CustomField>
    <fullName>EstimatedCompletionDate__c</fullName>
    <description>Displays the Estimated Completion Date. It is being calculated as Relative Days to complete (unique to each task) added to the Journey&apos;s Onboarding Start Date.</description>
    <formula>Journey__r.OnboardingStartDate__c + RelativeDaystoComplete__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimated Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Creates a Master-detail Relationship between Journey and its personal Tasks.</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Tasks</relationshipLabel>
    <relationshipName>Journey_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/fields/RelativeDaystoComplete__c.field-meta.xml
<CustomField>
    <fullName>RelativeDaystoComplete__c</fullName>
    <description>Indicates the period in which the Task needs to be completed.</description>
    <label>Relative Days to Complete</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/fields/TaskRequirements__c.field-meta.xml
<CustomField>
    <fullName>TaskRequirements__c</fullName>
    <description>Display the Completion Requirements for each Task. Steps to be completed.</description>
    <label>Task Requirements</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>A Task Template which includes several steps that each role needs to complete in order to reach their probation requirements.</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TemplateTask__c/TemplateTask__c.object-meta.xml
<CustomObject>
    <description>Create tasks specific to the Template object.</description>
    <label>Template Task</label>
    <nameField>
        <label>Template Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TemplateTask__c/fields/RelativeDaystoComplete__c.field-meta.xml
<CustomField>
    <fullName>RelativeDaystoComplete__c</fullName>
    <description>Indicates the time in which the Task needs to be completed.</description>
    <label>Relative Days to Complete</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TemplateTask__c/fields/TaskRequirements__c.field-meta.xml
<CustomField>
    <fullName>TaskRequirements__c</fullName>
    <description>Display the Task requirements to be completed.</description>
    <label>Task Requirements</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TemplateTask__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <description>A Master-detail relationship that connects each task to its Template.</description>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Template Tasks</relationshipLabel>
    <relationshipName>Template_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/bg_DataAccessor.cls
public inherited sharing class bg_DataAccessor {
    
    public static List<Template__c> getTemplateTasksInfo(List<Id> templateIds)
    {
        List<Template__c> templateInfo = [SELECT Id, Name, (SELECT Id, Name, TaskRequirements__c, RelativeDaystoComplete__c FROM Template_Tasks__r) 
                                FROM Template__c WHERE Id IN :templateIds WITH SECURITY_ENFORCED];
        
        return templateInfo;
    }

    public static List<JourneyTask__c> getJourneyTasks(Id journeyId)
    {
        return [SELECT Id, Name, CompletionStatus__c, EstimatedCompletionDate__c, RelativeDaystoComplete__c, TaskRequirements__c
                FROM JourneyTask__c 
                WHERE Journey__c = :journeyId WITH SECURITY_ENFORCED];           
    }

    public static Database.QueryLocator getOverdueInProgressJourneyTasks()
    {
        return Database.getQueryLocator([SELECT Name, CompletionStatus__c, Journey__r.CandidateName__c, EstimatedCompletionDate__c 
                                        FROM JourneyTask__c 
                                        WHERE CompletionStatus__c = 'Overdue' 
                                        OR (CompletionStatus__c = 'In Progress' AND EstimatedCompletionDate__c <= NEXT_N_DAYS:7) 
                                        ORDER BY Journey__r.CandidateName__c, EstimatedCompletionDate__c ASC
                                        NULLS LAST]);
    }
    
}