force-app/main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <description>Candidate Progress Tracking</description>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journey__c/fields/CandidateName__c.field-meta.xml
<CustomField>
    <fullName>CandidateName__c</fullName>
    <description>Candidate Name</description>
    <label>Candidate Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journey__c/fields/OnboardingStartDate__c.field-meta.xml
<CustomField>
    <fullName>OnboardingStartDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Onboarding Start Date</description>
    <label>Onboarding Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/JourneyTask__c.object-meta.xml
<CustomObject>
    <description>Add a Task related to the Journey Object.</description>
    <label>Journey Task</label>
    <nameField>
        <label>Journey Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journey Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JourneyTask__c/fields/CompletionStatus__c.field-meta.xml
<CustomField>
    <fullName>CompletionStatus__c</fullName>
    <description>Indicates the status for each task.</description>
    <formula>IF( Completed__c , &quot;Complete&quot;, IF( Today() &gt; EstimatedCompletionDate__c , &quot;Overdue&quot;, &quot;In Progress&quot;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Completion Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/fields/EstimatedCompletionDate__c.field-meta.xml
<CustomField>
    <fullName>EstimatedCompletionDate__c</fullName>
    <description>Displays the Estimated Completion Date. It is being calculated as Relative Days to complete (unique to each task) added to the Journey&apos;s Onboarding Start Date.</description>
    <formula>Journey__r.OnboardingStartDate__c + RelativeDaystoComplete__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimated Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Creates a Master-detail Relationship between Journey and its personal Tasks.</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Tasks</relationshipLabel>
    <relationshipName>Journey_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/bg_JourneyTasksProgressEmailHelper_Test.cls
@isTest
private class bg_JourneyTasksProgressEmailHelper_Test {
    @isTest
    static void displayTasksIntoHtmlBodyTest_WithTasks()
    {
        Integer batchSize = 2000;
        Journey__c journey = bg_JourneyService_DataFactory.createSingleJourneyWithoutTemplate();
        journey.OnboardingStartDate__c = date.today().addDays(-10);
        insert journey;
        List<JourneyTask__c> journeyTasksOverdue = bg_JourneyService_DataFactory.createJourneyTasks(batchSize/2, journey, 7);
        insert journeyTasksOverdue;
        List<JourneyTask__c> journeyTasksInProgress = bg_JourneyService_DataFactory.createJourneyTasks(batchSize/2, journey, 15);
        insert journeyTasksInProgress;
        List<JourneyTask__c> journeyTasksScope = [SELECT Name, CompletionStatus__c, Journey__r.CandidateName__c, EstimatedCompletionDate__c 
                                            FROM JourneyTask__c 
                                            WHERE CompletionStatus__c = 'Overdue' 
                                            OR (CompletionStatus__c = 'In Progress' AND EstimatedCompletionDate__c <= NEXT_N_DAYS:7) 
                                            ORDER BY Journey__r.CandidateName__c, EstimatedCompletionDate__c ASC
                                            NULLS LAST];

        List<JourneyTask__c> tasksInProgressDueWithinWeek = [SELECT Name, CompletionStatus__c, Journey__r.CandidateName__c, EstimatedCompletionDate__c 
                                                            FROM JourneyTask__c 
                                                            WHERE CompletionStatus__c = 'In Progress' AND EstimatedCompletionDate__c <= NEXT_N_DAYS:7
                                                            ORDER BY Journey__r.CandidateName__c, EstimatedCompletionDate__c ASC
                                                            NULLS LAST];

        List<JourneyTask__c> tasksOverdue = [SELECT Name, CompletionStatus__c, Journey__r.CandidateName__c, EstimatedCompletionDate__c 
                                            FROM JourneyTask__c 
                                            WHERE CompletionStatus__c = 'Overdue'
                                            ORDER BY Journey__r.CandidateName__c, EstimatedCompletionDate__c ASC
                                            NULLS LAST];

        Test.startTest();
        bg_JourneyTasksProgressEmailHelper.displayTasksIntoHtmlBody(journeyTasksScope);
        Test.stopTest();

        System.assertEquals(tasksInProgressDueWithinWeek.size(), bg_JourneyTasksProgressEmailHelper.recordsDueWithinWeekProcessed, 
            'Number of tasks In Progress due within next week, should be equal ' + tasksInProgressDueWithinWeek.size() + '.');
        System.assertEquals(tasksOverdue.size(), bg_JourneyTasksProgressEmailHelper.overdueRecordsProcessed, 
            'Number of Overdue Tasks should be ' + tasksOverdue.size() + '.');
        System.assertEquals(journeyTasksScope.size(), bg_JourneyTasksProgressEmailHelper.totalRecordsProcessed, 
            'Total number of Records Processed shoule be equal ' + journeyTasksScope.size() +'.');
    }

    @isTest
    static void displayTasksIntoHtmlBodyTest_WithoutAnyTasks()
    {
        Journey__c journey = bg_JourneyService_DataFactory.createSingleJourneyWithoutTemplate();
        insert journey;

        List<JourneyTask__c> journeyTasksScope = [SELECT Name, CompletionStatus__c, Journey__r.CandidateName__c, EstimatedCompletionDate__c 
                                            FROM JourneyTask__c 
                                            WHERE CompletionStatus__c = 'Overdue' 
                                            OR (CompletionStatus__c = 'In Progress' AND EstimatedCompletionDate__c <= NEXT_N_DAYS:7) 
                                            ORDER BY Journey__r.CandidateName__c, EstimatedCompletionDate__c ASC
                                            NULLS LAST];

        List<JourneyTask__c> tasksInProgressDueWithinWeek = [SELECT Name, CompletionStatus__c, Journey__r.CandidateName__c, EstimatedCompletionDate__c 
                                            FROM JourneyTask__c 
                                            WHERE CompletionStatus__c = 'In Progress' AND EstimatedCompletionDate__c <= NEXT_N_DAYS:7
                                            ORDER BY Journey__r.CandidateName__c, EstimatedCompletionDate__c ASC
                                            NULLS LAST];

        List<JourneyTask__c> tasksOverdue = [SELECT Name, CompletionStatus__c, Journey__r.CandidateName__c, EstimatedCompletionDate__c 
                            FROM JourneyTask__c 
                            WHERE CompletionStatus__c = 'Overdue'
                            ORDER BY Journey__r.CandidateName__c, EstimatedCompletionDate__c ASC
                            NULLS LAST];

        Test.startTest();
        bg_JourneyTasksProgressEmailHelper.displayTasksIntoHtmlBody(journeyTasksScope);
        Test.stopTest();
        
        System.assertEquals(journeyTasksScope.size(), bg_JourneyTasksProgressEmailHelper.totalRecordsProcessed, 
            'Number of Tasks should be zero');
        System.assertEquals(tasksInProgressDueWithinWeek.size(), bg_JourneyTasksProgressEmailHelper.recordsDueWithinWeekProcessed, 
            'Number of Tasks should be zero');
        System.assertEquals(tasksOverdue.size(), bg_JourneyTasksProgressEmailHelper.overdueRecordsProcessed, 
            'Number of Overdue Tasks should be zero');
    }

    @isTest
    static void displayTasksIntoHtmlBodyTest_OnlyOverdue()
    {
        Integer batchSize = 2000;
        Journey__c journey = bg_JourneyService_DataFactory.createSingleJourneyWithoutTemplate();
        journey.OnboardingStartDate__c = date.today().addDays(-10);
        insert journey;
        List<JourneyTask__c> journeyTasksOverdue = bg_JourneyService_DataFactory.createJourneyTasks(batchSize/2, journey, 7);
        insert journeyTasksOverdue;

        List<JourneyTask__c> journeyTasksScope = [SELECT Name, CompletionStatus__c, Journey__r.CandidateName__c, EstimatedCompletionDate__c 
                                            FROM JourneyTask__c 
                                            WHERE CompletionStatus__c = 'Overdue' 
                                            OR (CompletionStatus__c = 'In Progress' AND EstimatedCompletionDate__c <= NEXT_N_DAYS:7) 
                                            ORDER BY Journey__r.CandidateName__c, EstimatedCompletionDate__c ASC
                                            NULLS LAST];

        List<JourneyTask__c> tasksOverdue = [SELECT Name, CompletionStatus__c, Journey__r.CandidateName__c, EstimatedCompletionDate__c 
                                            FROM JourneyTask__c 
                                            WHERE CompletionStatus__c = 'Overdue'
                                            ORDER BY Journey__r.CandidateName__c, EstimatedCompletionDate__c ASC
                                            NULLS LAST];
                                            
        List<JourneyTask__c> tasksInProgressDueWithinWeek = [SELECT Name, CompletionStatus__c, Journey__r.CandidateName__c, EstimatedCompletionDate__c 
                                            FROM JourneyTask__c 
                                            WHERE CompletionStatus__c = 'In Progress' AND EstimatedCompletionDate__c <= NEXT_N_DAYS:7
                                            ORDER BY Journey__r.CandidateName__c, EstimatedCompletionDate__c ASC
                                            NULLS LAST];

        Test.startTest();
        bg_JourneyTasksProgressEmailHelper.displayTasksIntoHtmlBody(journeyTasksScope);
        Test.stopTest();

        System.assertEquals(tasksOverdue.size(), bg_JourneyTasksProgressEmailHelper.overdueRecordsProcessed, 
            'Number of Overdue Tasks should be ' + tasksOverdue.size() + '.');
        System.assertEquals(journeyTasksScope.size(), bg_JourneyTasksProgressEmailHelper.totalRecordsProcessed, 
            'Total number of Records Processed shoule be equal ' + journeyTasksScope.size() +'.');
        System.assertEquals(tasksInProgressDueWithinWeek.size(), bg_JourneyTasksProgressEmailHelper.recordsDueWithinWeekProcessed, 
            'Number of Tasks should be zero');
        }

    @isTest
    static void displayTasksIntoHtmlBodyTest_OnlyDueWithinWeek()
    {
        Integer batchSize = 2000;
        Journey__c journey = bg_JourneyService_DataFactory.createSingleJourneyWithoutTemplate();
        journey.OnboardingStartDate__c = date.today().addDays(-10);
        insert journey;
        List<JourneyTask__c> journeyTasksInProgress = bg_JourneyService_DataFactory.createJourneyTasks(batchSize/2, journey, 15);
        insert journeyTasksInProgress;

        List<JourneyTask__c> journeyTasksScope = [SELECT Name, CompletionStatus__c, Journey__r.CandidateName__c, EstimatedCompletionDate__c 
                                            FROM JourneyTask__c 
                                            WHERE CompletionStatus__c = 'Overdue' 
                                            OR (CompletionStatus__c = 'In Progress' AND EstimatedCompletionDate__c <= NEXT_N_DAYS:7) 
                                            ORDER BY Journey__r.CandidateName__c, EstimatedCompletionDate__c ASC
                                            NULLS LAST];

        List<JourneyTask__c> tasksInProgressDueWithinWeek = [SELECT Name, CompletionStatus__c, Journey__r.CandidateName__c, EstimatedCompletionDate__c 
                                                            FROM JourneyTask__c 
                                                            WHERE CompletionStatus__c = 'In Progress' AND EstimatedCompletionDate__c <= NEXT_N_DAYS:7
                                                            ORDER BY Journey__r.CandidateName__c, EstimatedCompletionDate__c ASC
                                                            NULLS LAST];

        List<JourneyTask__c> tasksOverdue = [SELECT Name, CompletionStatus__c, Journey__r.CandidateName__c, EstimatedCompletionDate__c 
                                                            FROM JourneyTask__c 
                                                            WHERE CompletionStatus__c = 'Overdue'
                                                            ORDER BY Journey__r.CandidateName__c, EstimatedCompletionDate__c ASC
                                                            NULLS LAST];

        Test.startTest();
        bg_JourneyTasksProgressEmailHelper.displayTasksIntoHtmlBody(journeyTasksScope);
        Test.stopTest();

        System.assertEquals(tasksInProgressDueWithinWeek.size(), bg_JourneyTasksProgressEmailHelper.recordsDueWithinWeekProcessed, 
            'Number of tasks In Progress due within next week, should be equal ' + tasksInProgressDueWithinWeek.size() + '.');
        System.assertEquals(journeyTasksScope.size(), bg_JourneyTasksProgressEmailHelper.totalRecordsProcessed, 
            'Total number of Records Processed shoule be equal ' + journeyTasksScope.size() +'.');
        System.assertEquals(tasksOverdue.size(), bg_JourneyTasksProgressEmailHelper.overdueRecordsProcessed, 
            'Number of Overdue Tasks should be zero');
    }
}