force-app/main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <description>Candidate Progress Tracking</description>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journey__c/fields/CandidateName__c.field-meta.xml
<CustomField>
    <fullName>CandidateName__c</fullName>
    <description>Candidate Name</description>
    <label>Candidate Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/JourneyTask__c.object-meta.xml
<CustomObject>
    <description>Add a Task related to the Journey Object.</description>
    <label>Journey Task</label>
    <nameField>
        <label>Journey Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journey Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JourneyTask__c/fields/CompletionStatus__c.field-meta.xml
<CustomField>
    <fullName>CompletionStatus__c</fullName>
    <description>Indicates the status for each task.</description>
    <formula>IF( Completed__c , &quot;Complete&quot;, IF( Today() &gt; EstimatedCompletionDate__c , &quot;Overdue&quot;, &quot;In Progress&quot;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Completion Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/fields/EstimatedCompletionDate__c.field-meta.xml
<CustomField>
    <fullName>EstimatedCompletionDate__c</fullName>
    <description>Displays the Estimated Completion Date. It is being calculated as Relative Days to complete (unique to each task) added to the Journey&apos;s Onboarding Start Date.</description>
    <formula>Journey__r.OnboardingStartDate__c + RelativeDaystoComplete__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimated Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Creates a Master-detail Relationship between Journey and its personal Tasks.</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Tasks</relationshipLabel>
    <relationshipName>Journey_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/bg_JourneyTasksProgressEmailHelper.cls
public inherited sharing class bg_JourneyTasksProgressEmailHelper {

    public static Integer overdueRecordsProcessed = 0;
    public static Integer recordsDueWithinWeekProcessed = 0;
    public static Integer totalRecordsProcessed = 0;
    public static String htmlBody;

    public static void displayTasksIntoHtmlBody(List<JourneyTask__c> scope)
    {
        for (JourneyTask__c result : scope)
        {
            String candidateName = result.Journey__r.CandidateName__c;
            String taskName = result.Name;
            String status = result.CompletionStatus__c;
            Date dueDate = result.EstimatedCompletionDate__c;
            String formattedDate = (dueDate.day() + '/' + dueDate.month() + '/' + dueDate.year());
                
            if (status == 'Overdue')
            {
                status = '<span style="color:red">' + (String)result.CompletionStatus__c + '</span>';
                overdueRecordsProcessed +=1;
            }
            else
            {
                status = '<span style="color:orange">' + (String)result.CompletionStatus__c + '</span>';
                recordsDueWithinWeekProcessed +=1;
            }  
            htmlBody += '<tr><td>'+ candidateName +'</td><td>'+ taskName +'</td><td>'+ status +'</td><td>'+ formattedDate +'</td></tr>';
        }
        totalRecordsProcessed += scope.size();
    }
}