force-app/main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <description>Candidate Progress Tracking</description>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journey__c/fields/CandidateEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>CandidateEmailAddress__c</fullName>
    <description>Candidate&apos;s Email Address</description>
    <label>Candidate Email Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Journey__c/fields/CandidateName__c.field-meta.xml
<CustomField>
    <fullName>CandidateName__c</fullName>
    <description>Candidate Name</description>
    <label>Candidate Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journey__c/fields/ManagerEmail__c.field-meta.xml
<CustomField>
    <fullName>ManagerEmail__c</fullName>
    <description>Manager&apos;s Email</description>
    <label>Manager Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Journey__c/fields/ManagerName__c.field-meta.xml
<CustomField>
    <fullName>ManagerName__c</fullName>
    <description>Manager&apos;s Name</description>
    <label>Manager Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journey__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Apply s specific Template to this Journey.</description>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/JourneyTask__c.object-meta.xml
<CustomObject>
    <description>Add a Task related to the Journey Object.</description>
    <label>Journey Task</label>
    <nameField>
        <label>Journey Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journey Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JourneyTask__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Creates a Master-detail Relationship between Journey and its personal Tasks.</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Tasks</relationshipLabel>
    <relationshipName>Journey_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/fields/RelativeDaystoComplete__c.field-meta.xml
<CustomField>
    <fullName>RelativeDaystoComplete__c</fullName>
    <description>Indicates the period in which the Task needs to be completed.</description>
    <label>Relative Days to Complete</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/fields/TaskRequirements__c.field-meta.xml
<CustomField>
    <fullName>TaskRequirements__c</fullName>
    <description>Display the Completion Requirements for each Task. Steps to be completed.</description>
    <label>Task Requirements</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>A Task Template which includes several steps that each role needs to complete in order to reach their probation requirements.</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TemplateTask__c/TemplateTask__c.object-meta.xml
<CustomObject>
    <description>Create tasks specific to the Template object.</description>
    <label>Template Task</label>
    <nameField>
        <label>Template Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TemplateTask__c/fields/RelativeDaystoComplete__c.field-meta.xml
<CustomField>
    <fullName>RelativeDaystoComplete__c</fullName>
    <description>Indicates the time in which the Task needs to be completed.</description>
    <label>Relative Days to Complete</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TemplateTask__c/fields/TaskRequirements__c.field-meta.xml
<CustomField>
    <fullName>TaskRequirements__c</fullName>
    <description>Display the Task requirements to be completed.</description>
    <label>Task Requirements</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TemplateTask__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <description>A Master-detail relationship that connects each task to its Template.</description>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Template Tasks</relationshipLabel>
    <relationshipName>Template_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/bg_JourneyService_DataFactory.cls
@isTest
public class bg_JourneyService_DataFactory {
    
    public static List<Template__c> createTemplates(Integer numTemplates)
    {
        List<Template__c> templates = new List<Template__c>();
        
        for (Integer i = 0; i < numTemplates; i++)
        {
            templates.add(new Template__c (Name='Template ' + i));
        }
        
        return templates;
    }
    
    public static Template__c createSingleTemplate()
    {
        return new Template__c(Name='Single Template');
    }
    
    public static List<TemplateTask__c> createTemplateTasks(Integer numTasks, Template__c template)
    {
        List<TemplateTask__c> templateTasks = new List<TemplateTask__c>();
        
        for (Integer i = 0; i < numTasks; i++)
        {
            templateTasks.add(new TemplateTask__c (Name='Template Task ' + i,
                                                   RelativeDaystoComplete__c = 30,
                                                   Template__c = template.Id));
        }
                           
        return templateTasks;
    }
    
    public static List<Journey__c> createJourneysWithTemplate(Integer numJourney, Template__c template)
    {
        List<Journey__c> journeys = new List<Journey__c>();
        
        for (Integer i = 0; i < numJourney; i++)
        {
            journeys.add(new Journey__c(Name='Journey with Template' + i,
                        				CandidateEmailAddress__c='candemail' + i + '@gmail.com',
                                        CandidateName__c='Cand Name ' + i,
                                        ManagerEmail__c='manageremail' + i + '@gmail.com',
                                        ManagerName__c='Manager Name ' + i,
                                        Template__c=template.Id));
        }
        
        return journeys;
    }    
    
  	public static List<Journey__c> createJourneysWithoutTemplate(Integer numJourney)
    {
        List<Journey__c> journeys = new List<Journey__c>();
        
        for (Integer i = 0; i < numJourney; i++)
        {
            journeys.add(new Journey__c(Name='Journey without Template' + i,
                        				CandidateEmailAddress__c='candemail' + i + '@gmail.com',
                                        CandidateName__c='Cand Name ' + i,
                                        ManagerEmail__c='manageremail' + i + '@gmail.com',
                                        ManagerName__c='Manager Name ' + i));
        }
        
        return journeys;
    } 
    
    public static Journey__c createSingleJourneyWithoutTemplate()
    {
        return new Journey__c(Name='Single Journey',
                        		CandidateEmailAddress__c='candemail@gmail.com',
                                CandidateName__c='Cand Name',
                                ManagerEmail__c='manageremail@gmail.com',
                                ManagerName__c='Manager Name');
    }
    
    public static Journey__c createSingleJourneyWithTemplate(Template__c template)
    {
        return new Journey__c(Name='Single Journey with Template',
                        				CandidateEmailAddress__c='candemail@gmail.com',
                                        CandidateName__c='Cand Name',
                                        ManagerEmail__c='manageremail@gmail.com',
                                        ManagerName__c='Manager Name',
                             			Template__c=template.Id);
    }

    public static List<JourneyTask__c> createJourneyTasks(Integer numTasks, Journey__c journey, Integer daysToComplete)
    {
        List<JourneyTask__c> journeyTasks = new List<JourneyTask__c>();
        for (Integer i = 0; i < numTasks; i++)
        {
            journeyTasks.add(new JourneyTask__c(Name='Journey Task ' + i,
                                                RelativeDaystoComplete__c = daysToComplete,
                                                TaskRequirements__c = '<p>Follow Instructions<p>',
                                                Journey__c = Journey.Id));
        }
        return journeyTasks;
    }
}