force-app/main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <description>Candidate Progress Tracking</description>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journey__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Apply s specific Template to this Journey.</description>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/JourneyTask__c.object-meta.xml
<CustomObject>
    <description>Add a Task related to the Journey Object.</description>
    <label>Journey Task</label>
    <nameField>
        <label>Journey Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journey Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JourneyTask__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Creates a Master-detail Relationship between Journey and its personal Tasks.</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Tasks</relationshipLabel>
    <relationshipName>Journey_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/fields/RelativeDaystoComplete__c.field-meta.xml
<CustomField>
    <fullName>RelativeDaystoComplete__c</fullName>
    <description>Indicates the period in which the Task needs to be completed.</description>
    <label>Relative Days to Complete</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/fields/TaskRequirements__c.field-meta.xml
<CustomField>
    <fullName>TaskRequirements__c</fullName>
    <description>Display the Completion Requirements for each Task. Steps to be completed.</description>
    <label>Task Requirements</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <description>A Task Template which includes several steps that each role needs to complete in order to reach their probation requirements.</description>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TemplateTask__c/TemplateTask__c.object-meta.xml
<CustomObject>
    <description>Create tasks specific to the Template object.</description>
    <label>Template Task</label>
    <nameField>
        <label>Template Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TemplateTask__c/fields/RelativeDaystoComplete__c.field-meta.xml
<CustomField>
    <fullName>RelativeDaystoComplete__c</fullName>
    <description>Indicates the time in which the Task needs to be completed.</description>
    <label>Relative Days to Complete</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TemplateTask__c/fields/TaskRequirements__c.field-meta.xml
<CustomField>
    <fullName>TaskRequirements__c</fullName>
    <description>Display the Task requirements to be completed.</description>
    <label>Task Requirements</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TemplateTask__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <description>A Master-detail relationship that connects each task to its Template.</description>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Template Tasks</relationshipLabel>
    <relationshipName>Template_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/bg_JourneyService.cls
public inherited sharing class bg_JourneyService implements bg_JourneyService_IF{

    public static Map<Id, List<TemplateTask__c>> pairTemplateWithTasks(List<Journey__c> journeys)
    {
        List<Id> storeTemplateIds = new List<Id>();
        
        for (Journey__c journey : journeys)
        {
            storeTemplateIds.add(journey.Template__c);
        }
        
        List<Template__c> templateTaskInfo = bg_DataAccessor.getTemplateTasksInfo(storeTemplateIds);
        Map<Id, List<TemplateTask__c>> templateTasksByTemplateId = new Map<Id, List<TemplateTask__c>>();
        
        for (Template__c temp : templateTaskInfo)
        {
            templateTasksByTemplateId.put(temp.Id, temp.Template_Tasks__r); 
        }
        
        return templateTasksByTemplateId;
    }
     
    public static void copyJourneyTasksFromTemplate(List<Journey__c> journeys)
    {
        Map<Id, List<TemplateTask__c>> templateTasksByTemplateId = pairTemplateWithTasks(journeys);
        List<JourneyTask__c> journeyTasks = new List<JourneyTask__c>();
        
        for (Journey__c journey : journeys)
            {
                if ((journey.Template__c != null) && (templateTasksByTemplateId.containsKey(journey.Template__c)))
                {
                    for (TemplateTask__c task : templateTasksByTemplateId.get(journey.Template__c))
                    {
                        journeyTasks.add(new JourneyTask__c(Name = task.Name, 
                                                RelativeDaystoComplete__c = task.RelativeDaystoComplete__c,
                                                TaskRequirements__c = task.TaskRequirements__c,
                                                Journey__c = journey.Id)); 
                    }  
                }
            }
        insert journeyTasks;
    }  

}