force-app/main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <description>Candidate Progress Tracking</description>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journey__c/fields/CandidateName__c.field-meta.xml
<CustomField>
    <fullName>CandidateName__c</fullName>
    <description>Candidate Name</description>
    <label>Candidate Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journey__c/fields/OnboardingStartDate__c.field-meta.xml
<CustomField>
    <fullName>OnboardingStartDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Onboarding Start Date</description>
    <label>Onboarding Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/JourneyTask__c.object-meta.xml
<CustomObject>
    <description>Add a Task related to the Journey Object.</description>
    <label>Journey Task</label>
    <nameField>
        <label>Journey Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journey Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JourneyTask__c/fields/CompletionStatus__c.field-meta.xml
<CustomField>
    <fullName>CompletionStatus__c</fullName>
    <description>Indicates the status for each task.</description>
    <formula>IF( Completed__c , &quot;Complete&quot;, IF( Today() &gt; EstimatedCompletionDate__c , &quot;Overdue&quot;, &quot;In Progress&quot;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Completion Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/fields/EstimatedCompletionDate__c.field-meta.xml
<CustomField>
    <fullName>EstimatedCompletionDate__c</fullName>
    <description>Displays the Estimated Completion Date. It is being calculated as Relative Days to complete (unique to each task) added to the Journey&apos;s Onboarding Start Date.</description>
    <formula>Journey__r.OnboardingStartDate__c + RelativeDaystoComplete__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimated Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/JourneyTask__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Creates a Master-detail Relationship between Journey and its personal Tasks.</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Tasks</relationshipLabel>
    <relationshipName>Journey_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/bg_JourneyTasksProgressSendEmail_Test.cls
@isTest
private class bg_JourneyTasksProgressSendEmail_Test {
   
    @isTest static void test_withTasks()
    {
        Integer batchSize = 2000;
        Journey__c journey = bg_JourneyService_DataFactory.createSingleJourneyWithoutTemplate();
        journey.OnboardingStartDate__c = date.today().addDays(-10);
        insert journey;
        List<JourneyTask__c> journeyTasksOverdue = bg_JourneyService_DataFactory.createJourneyTasks(batchSize/2, journey, 7);
        insert journeyTasksOverdue;
        List<JourneyTask__c> journeyTasksInProgress = bg_JourneyService_DataFactory.createJourneyTasks(batchSize/2, journey, 15);
        insert journeyTasksInProgress;
        Integer numOfErrorsAssert = 0;

        Test.startTest();
        bg_JourneyTasksProgressSendEmail sendEmail = new bg_JourneyTasksProgressSendEmail();
        Id jobId = Database.executeBatch(sendEmail, batchSize);
        Test.stopTest();
        
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
                            FROM AsyncApexJob WHERE Id =:jobId];

        List<JourneyTask__c> scope = [SELECT Name, CompletionStatus__c, Journey__r.CandidateName__c, EstimatedCompletionDate__c 
                                        FROM JourneyTask__c 
                                        WHERE CompletionStatus__c = 'Overdue' 
                                        OR (CompletionStatus__c = 'In Progress' AND EstimatedCompletionDate__c <= NEXT_N_DAYS:7) 
                                        ORDER BY Journey__r.CandidateName__c, EstimatedCompletionDate__c ASC];
        
        System.assertEquals(batchSize, scope.size(), 'Number of Journey Tasks records returned, should be ' + batchSize);
        System.assertEquals(batchSize/2, [SELECT count() FROM JourneyTask__c WHERE CompletionStatus__c = 'Overdue'], 
                            'Number of Overdue Journey Tasks records returned, should be ' + batchSize/2);
        System.assertEquals(batchSize/2, [SELECT count() FROM JourneyTask__c WHERE CompletionStatus__c = 'In Progress' AND EstimatedCompletionDate__c <= NEXT_N_DAYS:7], 
                            'Number of In Progress Journey Tasks records returned, should be ' + batchSize/2);
        System.assertEquals('Completed', a.Status, 'Job has failed to complete.');
        System.assertEquals(numOfErrorsAssert, a.NumberOfErrors, 'There was(were) ' + a.NumberOfErrors + 'error(s) when tried to process this job.');    
    }
    
    @isTest static void test_withoutTasks()
    {
        Integer batchSize = 2000;
        Test.startTest();
        bg_JourneyTasksProgressSendEmail sendEmail = new bg_JourneyTasksProgressSendEmail();
        Id jobId = Database.executeBatch(sendEmail, batchSize);
        Test.stopTest();
        
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
                            FROM AsyncApexJob WHERE Id =:jobId];
        
        List<JourneyTask__c> scope = [SELECT Name, CompletionStatus__c, Journey__r.CandidateName__c, EstimatedCompletionDate__c 
                                        FROM JourneyTask__c 
                                        WHERE CompletionStatus__c = 'Overdue' 
                                        OR (CompletionStatus__c = 'In Progress' AND EstimatedCompletionDate__c <= NEXT_N_DAYS:7) 
                                        ORDER BY Journey__r.CandidateName__c, EstimatedCompletionDate__c ASC];
        
        System.assertEquals(true, scope.isEmpty(), 'Tasks List should be empty.');
        System.assertEquals('Completed', a.Status, 'Job has failed to be completed, it should have gone through with 0 records to process.');
    }
}